language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: npvV/NfEFfmiXJbFeru+iojUfBwOOWAC5gYSxXSQS7T2dnzaOX66kQMnU1o1RTqFqJullRrsLQCgpUFeCW1jDJs2MqgzE2PtMyfCyxGkui5wurMCHsohmxIuKIA7GD+Jx3BW+HZ4VWusCtmcvT5RuoclnBXfMYMWRDDcCsAVy8qquLTm+fo8J7SmjZwbyYomfrIp2uClB0kpeLtPl0ngNXbiquhlNZxgaNefz0OicNbzU/D+qfsssN88Z7aYw1MHgkV0VDi7a1cg4mv5r+0oAQ6s7IASen/Mi7BQFjj1TwgZm2byaWCUU3smWjaH4fjcH8C+1SSI2U23Ke7RhUlg6+d14Kvl97idRlyzzGnKoIEkYT6EcFSfQJFRPf13zzOfoww6dh1sjiQXJjMf6zjGsDRo+Y2/mMbxrRQ72M/dVQ9wKmahG8hQX2Pr/0EnpzLjrXWy7Jrf1ZaP+A7jSTC+eBLUGLEDO1pqo/K7PDeT1Sla8Nt0eSJsDQPaTBtULkNgh1h8Tj3KYRUOMyL8pJLbLPYF4AsJ9JRqRK/ELmrI+PtxVm1st+0I4XGhT5J3NMxg4kIF6PQoEfPTDEN9PCWXGCi5FUEJOt2pX+G4+DJli34Tyr8rFeAfRtPfCoGjcHyu6lNzwva/FFvHCY/TPwfBTUUqb5pqF5ImXm4Qvs351iE=
  app: secret-garden-14097
